name: Slither

on:
  push:
    branches: [ certora-audits ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CERTORAKEY: ${{ secrets.CERTORAKEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.5.11/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc
          pip3 install certora-cli

      - name: Verify with Certora
        run: |
          cd contracts
          yarn install
          ../spec/scripts/runPrivilegedOUSD.sh
          ../spec/scripts/runPrivilegedVaultAdmin.sh
